"""Module: Params - AvNav-shaped editable parameter specifications.

Documentation: documentation/user/configuration.md
Depends: none
"""

from __future__ import annotations

CONFIG_PARAMETERS: list[dict[str, object]] = [
    {
        "name": "sample_interval",
        "type": "FLOAT",
        "default": "1.0",
        "rangeOrList": [0.5, 5.0],
        "description": "Seconds between store value reads",
    },
    {
        "name": "percentile",
        "type": "NUMBER",
        "default": "65",
        "rangeOrList": [1, 99],
        "description": "Percentile for polar speed extraction",
    },
    {
        "name": "flush_interval",
        "type": "NUMBER",
        "default": "300",
        "rangeOrList": [60, 3600],
        "description": "Seconds between persistence flushes",
    },
    {
        "name": "stale_threshold",
        "type": "FLOAT",
        "default": "3.0",
        "rangeOrList": [1.0, 30.0],
        "description": "Max age for a store value before it is stale",
    },
    {
        "name": "age_skew_threshold",
        "type": "FLOAT",
        "default": "2.0",
        "rangeOrList": [0.5, 10.0],
        "description": "Max timestamp difference between core values",
    },
    {
        "name": "max_tws",
        "type": "NUMBER",
        "default": "60",
        "rangeOrList": [20, 60],
        "description": "Max plausible true wind speed in knots",
    },
    {
        "name": "max_stw",
        "type": "NUMBER",
        "default": "40",
        "rangeOrList": [10, 80],
        "description": "Max plausible speed through water in knots",
    },
    {
        "name": "low_wind_threshold",
        "type": "FLOAT",
        "default": "3.0",
        "rangeOrList": [0.5, 10.0],
        "description": "TWS below this is rejected",
    },
    {
        "name": "head_to_wind_threshold",
        "type": "NUMBER",
        "default": "10",
        "rangeOrList": [5, 30],
        "description": "TWA abs below this is rejected",
    },
    {
        "name": "anchored_stw_threshold",
        "type": "FLOAT",
        "default": "0.3",
        "rangeOrList": [0.1, 1.0],
        "description": "STW below this with wind is rejected",
    },
    {
        "name": "twa_roc_threshold",
        "type": "FLOAT",
        "default": "15.0",
        "rangeOrList": [5.0, 45.0],
        "description": "Max TWA change in degrees per second",
    },
    {
        "name": "tws_roc_threshold",
        "type": "FLOAT",
        "default": "10.0",
        "rangeOrList": [3.0, 30.0],
        "description": "Max TWS change in knots per second",
    },
    {
        "name": "stw_roc_threshold",
        "type": "FLOAT",
        "default": "2.0",
        "rangeOrList": [0.5, 10.0],
        "description": "Max STW change in knots per second",
    },
    {
        "name": "cooldown_seconds",
        "type": "NUMBER",
        "default": "30",
        "rangeOrList": [5, 120],
        "description": "Seconds to reject after maneuver detection",
    },
    {
        "name": "stability_window_seconds",
        "type": "NUMBER",
        "default": "15",
        "rangeOrList": [5, 60],
        "description": "Seconds of stable values required",
    },
    {
        "name": "stability_twa_range",
        "type": "FLOAT",
        "default": "20.0",
        "rangeOrList": [5.0, 45.0],
        "description": "Max TWA range in stability window",
    },
    {
        "name": "stability_tws_range",
        "type": "FLOAT",
        "default": "10.0",
        "rangeOrList": [3.0, 20.0],
        "description": "Max TWS range in stability window",
    },
    {
        "name": "stability_stw_range",
        "type": "FLOAT",
        "default": "4.0",
        "rangeOrList": [1.0, 10.0],
        "description": "Max STW range in stability window",
    },
    {
        "name": "engine_tws_ceil",
        "type": "FLOAT",
        "default": "5.0",
        "rangeOrList": [2.0, 15.0],
        "description": "TWS ceiling for engine-suspected quarantine",
    },
    {
        "name": "engine_stw_floor",
        "type": "FLOAT",
        "default": "3.0",
        "rangeOrList": [1.0, 10.0],
        "description": "STW floor for engine-suspected quarantine",
    },
    {
        "name": "min_samples_for_export",
        "type": "NUMBER",
        "default": "10",
        "rangeOrList": [3, 100],
        "description": "High-confidence export sample floor",
    },
    {
        "name": "debug_logging",
        "type": "BOOLEAN",
        "default": "false",
        "description": "Enable verbose debug logging of sample decisions",
    },
    {
        "name": "enh_rpm_enabled",
        "type": "BOOLEAN",
        "default": "true",
        "description": "Enable engine-RPM reject (R17)",
    },
    {
        "name": "enh_rpm_key",
        "type": "STRING",
        "default": "",
        "description": "Store key for engine RPM",
    },
    {
        "name": "enh_rpm_idle_max",
        "type": "NUMBER",
        "default": "900",
        "rangeOrList": [200, 4000],
        "description": "RPM above this rejects the sample as motoring (R17)",
    },
    {
        "name": "enh_engine_state_enabled",
        "type": "BOOLEAN",
        "default": "true",
        "description": "Enable engine-state reject (R18)",
    },
    {
        "name": "enh_engine_state_key",
        "type": "STRING",
        "default": "",
        "description": "Store key for engine state (boolean, RPM, alternator voltage, ...)",
    },
    {
        "name": "enh_engine_state_on_threshold",
        "type": "FLOAT",
        "default": "0.5",
        "rangeOrList": [0.0, 10000.0],
        "description": "engine_signal at/above this means on (boolean 0.5, RPM ~50, volts ~13.2)",
    },
    {
        "name": "enh_depth_enabled",
        "type": "BOOLEAN",
        "default": "true",
        "description": "Enable shallow-water reject (R19)",
    },
    {
        "name": "enh_depth_key",
        "type": "STRING",
        "default": "gps.depthBelowKeel",
        "description": "Store key for depth in meters (defaults to depth below keel)",
    },
    {
        "name": "enh_depth_floor_m",
        "type": "FLOAT",
        "default": "1.0",
        "rangeOrList": [0.5, 50.0],
        "description": "Clearance below this rejects the sample (shallow-water squat)",
    },
    {
        "name": "enh_slip_enabled",
        "type": "BOOLEAN",
        "default": "true",
        "description": "Enable STW-implausibly-low reject (R20)",
    },
    {
        "name": "enh_sog_key",
        "type": "STRING",
        "default": "gps.speed",
        "description": "Store key for speed over ground",
    },
    {
        "name": "enh_current_drift_key",
        "type": "STRING",
        "default": "gps.currentDrift",
        "description": "Store key for current drift; corroborates the R20 SOG/STW check",
    },
    {
        "name": "enh_slip_sog_floor_kt",
        "type": "FLOAT",
        "default": "1.0",
        "rangeOrList": [0.3, 10.0],
        "description": "SOG must exceed this for R20 to apply (boat clearly moving)",
    },
    {
        "name": "enh_slip_ratio",
        "type": "FLOAT",
        "default": "0.5",
        "rangeOrList": [0.1, 0.9],
        "description": "Reject when STW < SOG * ratio and current cannot explain the gap (R20)",
    },
    {
        "name": "enh_tw_crosscheck_enabled",
        "type": "BOOLEAN",
        "default": "true",
        "description": "Enable apparent/true-wind cross-check reject (R21)",
    },
    {
        "name": "enh_awa_key",
        "type": "STRING",
        "default": "gps.windAngle",
        "description": "Store key for apparent wind angle",
    },
    {
        "name": "enh_aws_key",
        "type": "STRING",
        "default": "gps.windSpeed",
        "description": "Store key for apparent wind speed",
    },
    {
        "name": "enh_tw_twa_tol_deg",
        "type": "FLOAT",
        "default": "15.0",
        "rangeOrList": [3.0, 45.0],
        "description": "Allowed TWA disagreement for the R21 true-wind cross-check",
    },
    {
        "name": "enh_tw_tws_tol_kt",
        "type": "FLOAT",
        "default": "3.0",
        "rangeOrList": [0.5, 15.0],
        "description": "Allowed TWS disagreement for the R21 true-wind cross-check",
    },
    {
        "name": "enh_heel_enabled",
        "type": "BOOLEAN",
        "default": "true",
        "description": "Enable heel-band reject (R22)",
    },
    {
        "name": "enh_heel_key",
        "type": "STRING",
        "default": "",
        "description": "Store key for heel/roll in degrees",
    },
    {
        "name": "enh_heel_min_deg",
        "type": "FLOAT",
        "default": "0.0",
        "rangeOrList": [0.0, 45.0],
        "description": "Reject below this absolute heel (0 disables it, multihull-safe)",
    },
    {
        "name": "enh_heel_max_deg",
        "type": "FLOAT",
        "default": "35.0",
        "rangeOrList": [5.0, 90.0],
        "description": "Reject above this absolute heel",
    },
    {
        "name": "enh_turnconfirm_enabled",
        "type": "BOOLEAN",
        "default": "true",
        "description": "Enable heading/COG turn confirmation for R11/R14",
    },
    {
        "name": "enh_heading_key",
        "type": "STRING",
        "default": "gps.headingTrue",
        "description": "Store key for heading",
    },
    {
        "name": "enh_cog_key",
        "type": "STRING",
        "default": "gps.track",
        "description": "Store key for course over ground",
    },
    {
        "name": "enh_turn_min_roc",
        "type": "FLOAT",
        "default": "3.0",
        "rangeOrList": [0.5, 30.0],
        "description": "Heading/COG deg/s at/above which a TWA spike is a real turn",
    },
]

EDITABLE_PARAMETERS: list[dict[str, object]] = []
